# -*- coding: utf-8 -*-
"""colab-e-ho-geldiniz-adl-not-defterinin-kopyas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/melisaaskaroglu8/016ad064067a07c3a7cb0d96b937087f/colab-e-ho-geldiniz-adl-not-defterinin-kopyas.ipynb
"""

import pandas as pd


veri = {
    "Bölge_Kodu": ["TR1", "TR2", "TR3", "TR4", "TR5", "TR6", "TR7", "TR8", "TR9", "TRA", "TRB", "TRC"],
    "Bölge_Adı": ["İstanbul", "Batı Marmara", "Ege", "Doğu Marmara", "Batı Anadolu", "Akdeniz", "Orta Anadolu", "Batı Karadeniz", "Doğu Karadeniz", "Kuzeydoğu Anadolu", "Ortadoğu Anadolu", "Güneydoğu Anadolu"],
    "Kasten Öldürme": [21.0, 2.9, 11.2, 9.3, 11.5, 13.0, 4.1, 5.2, 3.8, 2.9, 6.4, 8.7],
    "Kasten Yaralama": [15.3, 3.1, 14.2, 10.5, 12.8, 11.6, 5.3, 4.8, 4.1, 2.5, 4.9, 10.9],
    "Cinsel Saldırı": [22.4, 2.8, 13.1, 9.5, 11.0, 12.4, 3.8, 4.2, 3.1, 2.0, 5.2, 10.5],
    "Çocukların Cinsel İstismarı": [18.5, 3.0, 12.8, 10.1, 11.5, 13.0, 4.2, 4.5, 3.6, 2.8, 5.5, 10.5],
    "Hırsızlık": [32.5, 3.7, 11.5, 9.2, 10.8, 11.2, 3.1, 3.5, 2.4, 1.5, 4.2, 6.4],
    "Yağma": [28.4, 3.5, 10.2, 8.5, 11.0, 12.5, 3.8, 3.2, 2.1, 1.8, 5.6, 9.4],
    "Dolandırıcılık": [25.6, 4.2, 11.8, 9.6, 12.5, 11.0, 4.0, 3.8, 2.5, 1.6, 4.8, 8.6],
    "Uyuşturucu Kullanım/Bulundurma": [19.8, 4.5, 13.5, 10.2, 11.8, 14.5, 3.5, 4.0, 2.8, 1.9, 5.5, 8.0],
    "Uyuşturucu İmal ve Ticareti": [21.5, 4.0, 12.2, 9.8, 11.0, 13.2, 3.2, 3.5, 2.6, 2.1, 6.2, 10.7],
    "Sahtecilik": [26.2, 3.8, 10.5, 8.6, 13.5, 10.8, 4.5, 4.0, 2.5, 1.8, 4.6, 9.2]
}

df = pd.DataFrame(veri)
df.to_excel("Bolgesel_Kadin_Adalet_Tehlike_Oranlari.xlsx", index=False)
print("✅ 1. Excel Dosyası Başarıyla Güncellendi!")

import gradio as gr
import pandas as pd


suclar_data = {
    "Bölge_Kodu": ["TR1", "TR2", "TR3", "TR4", "TR5", "TR6", "TR7", "TR8", "TR9", "TRA", "TRB", "TRC"],
    "Bölge_Adı": ["İstanbul", "Batı Marmara", "Ege", "Doğu Marmara", "Batı Anadolu", "Akdeniz", "Orta Anadolu", "Batı Karadeniz", "Doğu Karadeniz", "Kuzeydoğu Anadolu", "Ortadoğu Anadolu", "Güneydoğu Anadolu"],
    "Kasten Öldürme": [21.0, 2.9, 11.2, 9.3, 11.5, 13.0, 4.1, 5.2, 3.8, 2.9, 6.4, 8.7],
    "Kasten Yaralama": [15.3, 3.1, 14.2, 10.5, 12.8, 11.6, 5.3, 4.8, 4.1, 2.5, 4.9, 10.9],
    "Cinsel Saldırı": [22.4, 2.8, 13.1, 9.5, 11.0, 12.4, 3.8, 4.2, 3.1, 2.0, 5.2, 10.5],
    "Çocukların Cinsel İstismarı": [18.5, 3.0, 12.8, 10.1, 11.5, 13.0, 4.2, 4.5, 3.6, 2.8, 5.5, 10.5],
    "Hırsızlık": [32.5, 3.7, 11.5, 9.2, 10.8, 11.2, 3.1, 3.5, 2.4, 1.5, 4.2, 6.4],
    "Yağma": [28.4, 3.5, 10.2, 8.5, 11.0, 12.5, 3.8, 3.2, 2.1, 1.8, 5.6, 9.4],
    "Dolandırıcılık": [25.6, 4.2, 11.8, 9.6, 12.5, 11.0, 4.0, 3.8, 2.5, 1.6, 4.8, 8.6],
    "Uyuşturucu Kullanım/Bulundurma": [19.8, 4.5, 13.5, 10.2, 11.8, 14.5, 3.5, 4.0, 2.8, 1.9, 5.5, 8.0],
    "Uyuşturucu İmal ve Ticareti": [21.5, 4.0, 12.2, 9.8, 11.0, 13.2, 3.2, 3.5, 2.6, 2.1, 6.2, 10.7],
    "Sahtecilik": [26.2, 3.8, 10.5, 8.6, 13.5, 10.8, 4.5, 4.0, 2.5, 1.8, 4.6, 9.2]
}
df_suclar = pd.DataFrame(suclar_data)

# Tırnak hatalarını önlemek için alt alta düzenlenmiş İl-Bölge veri listesi
iller_listesi = [
    {"İl_Adı": "İstanbul", "Bölge_Kodu": "TR1", "Bölge_Adı": "İstanbul", "Kritik_Bolgeler": "⚠️ Bağcılar, Esenyurt, Gaziosmanpaşa, Tarlabaşı (Beyoğlu), Dolapdere, Aksaray (Fatih), Sultanbeyli. (Özellikle ara sokaklar ve ıssız parklar gece saatlerinde yüksek risk taşımaktadır.)"},
    {"İl_Adı": "Ankara", "Bölge_Kodu": "TR5", "Bölge_Adı": "Batı Anadolu", "Kritik_Bolgeler": "⚠️ Altındağ (Çinçin, Hıdırlıktepe), Mamak, Sincan arka mahalleleri, Ulus rüzgarlı sokak civarı."},
    {"İl_Adı": "İzmir", "Bölge_Kodu": "TR3", "Bölge_Adı": "Ege", "Kritik_Bolgeler": "⚠️ Konak (Basmane, Kadifekale, Tepecik, İkiçeşmelik), Bornova (arka sokaklar/Doğanlar), Bayraklı (gecekondu bölgeleri)."},
    {"İl_Adı": "Bursa", "Bölge_Kodu": "TR4", "Bölge_Adı": "Doğu Marmara", "Kritik_Bolgeler": "⚠️ Yıldırım (Yavuzselim, Beyazıt), Osmangazi'nin bazı ücra kenar mahalleleri."},
    {"İl_Adı": "Antalya", "Bölge_Kodu": "TR6", "Bölge_Adı": "Akdeniz", "Kritik_Bolgeler": "⚠️ Kepez'in bazı ücra mahalleleri, Zeytinköy (Yeşildere) bölgesi."},
    {"İl_Adı": "Adana", "Bölge_Kodu": "TR6", "Bölge_Adı": "Akdeniz", "Kritik_Bolgeler": "⚠️ Yüreğir (Kiremithane, Çamlıbel), Seyhan (Hürriyet, Barbaros mahalleleri)."},
    {"İl_Adı": "Mersin", "Bölge_Kodu": "TR6", "Bölge_Adı": "Akdeniz", "Kritik_Bolgeler": "⚠️ Akdeniz ilçesinin bazı kenar mahalleleri, Toroslar arka sokakları."},
    {"İl_Adı": "Gaziantep", "Bölge_Kodu": "TRC", "Bölge_Adı": "Güneydoğu Anadolu", "Kritik_Bolgeler": "⚠️ Şahinbey ve Şehitkamil ilçelerinin bazı kuytu ve düzensiz göç alan dış mahalleleri."},
    {"İl_Adı": "Diyarbakır", "Bölge_Kodu": "TRC", "Bölge_Adı": "Güneydoğu Anadolu", "Kritik_Bolgeler": "⚠️ Bağlar ilçesinin bazı ara sokakları, Sur içi (ıssız ve restorasyon görmemiş eski sokaklar)."},
    {"İl_Adı": "Eskişehir", "Bölge_Kodu": "TR4", "Bölge_Adı": "Doğu Marmara", "Kritik_Bolgeler": "⚠️ Tepebaşı (Şirintepe arka sokakları), Odunpazarı (kuytu ve sanayi çevreleri). Gece geç saatlerde barlar sokağı çıkışlarına dikkat edilmelidir."},
    {"İl_Adı": "Bilecik", "Bölge_Kodu": "TR4", "Bölge_Adı": "Doğu Marmara", "Kritik_Bolgeler": "⚠️ İstasyon çevresi ıssız alanlar, sanayi bölgesi çevreleri ve üniversite dışındaki karanlık park/yürüyüş yolları dâhil tenha bölgeler."},
    {"İl_Adı": "Edirne", "Bölge_Kodu": "TR2", "Bölge_Adı": "Batı Marmara", "Kritik_Bolgeler": "⚠️ İstasyon arkası ve göç alan varoş mahalleler."},
    {"İl_Adı": "Kırklareli", "Bölge_Kodu": "TR2", "Bölge_Adı": "Batı Marmara", "Kritik_Bolgeler": "⚠️ Issız parklar ve gece geç saatte terminal çevreleri."},
    {"İl_Adı": "Tekirdağ", "Bölge_Kodu": "TR2", "Bölge_Adı": "Batı Marmara", "Kritik_Bolgeler": "⚠️ Çorlu ve Çerkezköy'ün bazı sanayi/kenar mahalleleri."},
    {"İl_Adı": "Balıkesir", "Bölge_Kodu": "TR2", "Bölge_Adı": "Batı Marmara", "Kritik_Bolgeler": "⚠️ Roman mahallelerinin kuytu kesimleri ve tenha sahiller."},
    {"İl_Adı": "Çanakkale", "Bölge_Kodu": "TR2", "Bölge_Adı": "Batı Marmara", "Kritik_Bolgeler": "⚠️ Gece tenha liman arkası ve sur dipleri."},
    {"İl_Adı": "Aydın", "Bölge_Kodu": "TR3", "Bölge_Adı": "Ege", "Kritik_Bolgeler": "⚠️ Efeler kenar mahalleleri."},
    {"İl_Adı": "Denizli", "Bölge_Kodu": "TR3", "Bölge_Adı": "Ege", "Kritik_Bolgeler": "⚠️ Otogar çevresi ve sanayi arkasındaki karanlık sokaklar."},
    {"İl_Adı": "Muğla", "Bölge_Kodu": "TR3", "Bölge_Adı": "Ege", "Kritik_Bolgeler": "⚠️ Bodrum/Marmaris barlar sokağı dışındaki tenha yollar."},
    {"İl_Adı": "Manisa", "Bölge_Kodu": "TR3", "Bölge_Adı": "Ege", "Kritik_Bolgeler": "⚠️ Turgutlu ve Salihli'nin bazı kuytu bölgeleri."},
    {"İl_Adı": "Afyonkarahisar", "Bölge_Kodu": "TR3", "Bölge_Adı": "Ege", "Kritik_Bolgeler": "⚠️ Kenar mahalleler ve ıssız park alanları."},
    {"İl_Adı": "Kütahya", "Bölge_Kodu": "TR3", "Bölge_Adı": "Ege", "Kritik_Bolgeler": "⚠️ Sanayi çevresi ve tenha ara sokaklar."},
    {"İl_Adı": "Uşak", "Bölge_Kodu": "TR3", "Bölge_Adı": "Ege", "Kritik_Bolgeler": "⚠️ Otogar çevresi ve ıssız sokaklar."},
    {"İl_Adı": "Kocaeli", "Bölge_Kodu": "TR4", "Bölge_Adı": "Doğu Marmara", "Kritik_Bolgeler": "⚠️ Gebze ve Dilovası'nın bazı sanayi/varoş mahalleleri."},
    {"İl_Adı": "Sakarya", "Bölge_Kodu": "TR4", "Bölge_Adı": "Doğu Marmara", "Kritik_Bolgeler": "⚠️ Erenler kenar sokakları."},
    {"İl_Adı": "Düzce", "Bölge_Kodu": "TR4", "Bölge_Adı": "Doğu Marmara", "Kritik_Bolgeler": "⚠️ Çevreyolu kenarları ve ıssız parklar."},
    {"İl_Adı": "Bolu", "Bölge_Kodu": "TR4", "Bölge_Adı": "Doğu Marmara", "Kritik_Bolgeler": "⚠️ Gece tenha parklar."},
    {"İl_Adı": "Yalova", "Bölge_Kodu": "TR4", "Bölge_Adı": "Doğu Marmara", "Kritik_Bolgeler": "⚠️ Merkez dışı göç alan varoş bölgeler."},
    {"İl_Adı": "Konya", "Bölge_Kodu": "TR5", "Bölge_Adı": "Batı Anadolu", "Kritik_Bolgeler": "⚠️ Karatay'ın bazı ücra mahalleleri."},
    {"İl_Adı": "Karaman", "Bölge_Kodu": "TR5", "Bölge_Adı": "Batı Anadolu", "Kritik_Bolgeler": "⚠️ Terminal çevresi."},
    {"İl_Adı": "Isparta", "Bölge_Kodu": "TR6", "Bölge_Adı": "Akdeniz", "Kritik_Bolgeler": "⚠️ Issız parklar."},
    {"İl_Adı": "Burdur", "Bölge_Kodu": "TR6", "Bölge_Adı": "Akdeniz", "Kritik_Bolgeler": "⚠️ Tenha parklar."},
    {"İl_Adı": "Hatay", "Bölge_Kodu": "TR6", "Bölge_Adı": "Akdeniz", "Kritik_Bolgeler": "⚠️ Sınır ve göç alan dış mahalleler."},
    {"İl_Adı": "Kahramanmaraş", "Bölge_Kodu": "TR6", "Bölge_Adı": "Akdeniz", "Kritik_Bolgeler": "⚠️ Kenar mahalleler."},
    {"İl_Adı": "Osmaniye", "Bölge_Kodu": "TR6", "Bölge_Adı": "Akdeniz", "Kritik_Bolgeler": "⚠️ Gece kuytu sokaklar."},
    {"İl_Adı": "Kırıkkale", "Bölge_Kodu": "TR7", "Bölge_Adı": "Orta Anadolu", "Kritik_Bolgeler": "⚠️ Issız otogar çevresi."},
    {"İl_Adı": "Aksaray", "Bölge_Kodu": "TR7", "Bölge_Adı": "Orta Anadolu", "Kritik_Bolgeler": "⚠️ Kenar mahalle kuytuları."},
    {"İl_Adı": "Niğde", "Bölge_Kodu": "TR7", "Bölge_Adı": "Orta Anadolu", "Kritik_Bolgeler": "⚠️ Tenha sokaklar."},
    {"İl_Adı": "Nevşehir", "Bölge_Kodu": "TR7", "Bölge_Adı": "Orta Anadolu", "Kritik_Bolgeler": "⚠️ Gece geç saatte ıssız parklar."},
    {"İl_Adı": "Kırşehir", "Bölge_Kodu": "TR7", "Bölge_Adı": "Orta Anadolu", "Kritik_Bolgeler": "⚠️ Kuytu mahalleler."},
    {"İl_Adı": "Kayseri", "Bölge_Kodu": "TR7", "Bölge_Adı": "Orta Anadolu", "Kritik_Bolgeler": "⚠️ Eski sanayi çevresi ve bazı ücra kenar mahalleleri."},
    {"İl_Adı": "Sivas", "Bölge_Kodu": "TR7", "Bölge_Adı": "Orta Anadolu", "Kritik_Bolgeler": "⚠️ Tenha sokaklar."},
    {"İl_Adı": "Yozgat", "Bölge_Kodu": "TR7", "Bölge_Adı": "Orta Anadolu", "Kritik_Bolgeler": "⚠️ Kenar mahalleler."},
    {"İl_Adı": "Zonguldak", "Bölge_Kodu": "TR8", "Bölge_Adı": "Batı Karadeniz", "Kritik_Bolgeler": "⚠️ Sanayi arkası ve tenha liman çevreleri."},
    {"İl_Adı": "Karabük", "Bölge_Kodu": "TR8", "Bölge_Adı": "Batı Karadeniz", "Kritik_Bolgeler": "⚠️ Issız terminal çevresi."},
    {"İl_Adı": "Bartın", "Bölge_Kodu": "TR8", "Bölge_Adı": "Batı Karadeniz", "Kritik_Bolgeler": "⚠️ Kenar mahalle kuytuları."},
    {"İl_Adı": "Kastamonu", "Bölge_Kodu": "TR8", "Bölge_Adı": "Batı Karadeniz", "Kritik_Bolgeler": "⚠️ Gece tenha parklar."},
    {"İl_Adı": "Çankırı", "Bölge_Kodu": "TR8", "Bölge_Adı": "Batı Karadeniz", "Kritik_Bolgeler": "⚠️ Issız alanlar."},
    {"İl_Adı": "Sinop", "Bölge_Kodu": "TR8", "Bölge_Adı": "Batı Karadeniz", "Kritik_Bolgeler": "⚠️ Gece tenha iskele arkası ve kuytu sokaklar."},
    {"İl_Adı": "Samsun", "Bölge_Kodu": "TR8", "Bölge_Adı": "Batı Karadeniz", "Kritik_Bolgeler": "⚠️ İlkadım kenar mahalleleri ve Canik'in bazı iç sokakları."},
    {"İl_Adı": "Tokat", "Bölge_Kodu": "TR8", "Bölge_Adı": "Batı Karadeniz", "Kritik_Bolgeler": "⚠️ Kuytu sokaklar."},
    {"İl_Adı": "Çorum", "Bölge_Kodu": "TR8", "Bölge_Adı": "Batı Karadeniz", "Kritik_Bolgeler": "⚠️ Çevreyolu kenarları."},
    {"İl_Adı": "Amasya", "Bölge_Kodu": "TR8", "Bölge_Adı": "Batı Karadeniz", "Kritik_Bolgeler": "⚠️ Issız parklar ve nehir kenarı tenha yerler."},
    {"İl_Adı": "Trabzon", "Bölge_Kodu": "TR9", "Bölge_Adı": "Doğu Karadeniz", "Kritik_Bolgeler": "⚠️ Çömlekçi mahallesi ara sokakları ve liman arkası."},
    {"İl_Adı": "Ordu", "Bölge_Kodu": "TR9", "Bölge_Adı": "Doğu Karadeniz", "Kritik_Bolgeler": "⚠️ Sanayi çevresi."},
    {"İl_Adı": "Giresun", "Bölge_Kodu": "TR9", "Bölge_Adı": "Doğu Karadeniz", "Kritik_Bolgeler": "⚠️ Issız liman arkası."},
    {"İl_Adı": "Rize", "Bölge_Kodu": "TR9", "Bölge_Adı": "Doğu Karadeniz", "Kritik_Bolgeler": "⚠️ Tenha sahil parkları ve kuytular."},
    {"İl_Adı": "Artvin", "Bölge_Kodu": "TR9", "Bölge_Adı": "Doğu Karadeniz", "Kritik_Bolgeler": "⚠️ Çevreyolları ve tenha yamaç yolları."},
    {"İl_Adı": "Gümüşhane", "Bölge_Kodu": "TR9", "Bölge_Adı": "Doğu Karadeniz", "Kritik_Bolgeler": "⚠️ Issız alanlar."},
    {"İl_Adı": "Erzurum", "Bölge_Kodu": "TRA", "Bölge_Adı": "Kuzeydoğu Anadolu", "Kritik_Bolgeler": "⚠️ Şehir merkezi dışındaki varoş/kenar mahalleler."},
    {"İl_Adı": "Erzincan", "Bölge_Kodu": "TRA", "Bölge_Adı": "Kuzeydoğu Anadolu", "Kritik_Bolgeler": "⚠️ Çevreyolu arkası ve tenha yollar."},
    {"İl_Adı": "Bayburt", "Bölge_Kodu": "TRA", "Bölge_Adı": "Kuzeydoğu Anadolu", "Kritik_Bolgeler": "⚠️ Tenha parklar ve nehir boyu ıssız yerler."},
    {"İl_Adı": "Ağrı", "Bölge_Kodu": "TRA", "Bölge_Adı": "Kuzeydoğu Anadolu", "Kritik_Bolgeler": "⚠️ Kenar mahalleler ve otogar çevresi."},
    {"İl_Adı": "Kars", "Bölge_Kodu": "TRA", "Bölge_Adı": "Kuzeydoğu Anadolu", "Kritik_Bolgeler": "⚠️ Issız otogar çevresi ve kale altı kuytu yerler."},
    {"İl_Adı": "Iğdır", "Bölge_Kodu": "TRA", "Bölge_Adı": "Kuzeydoğu Anadolu", "Kritik_Bolgeler": "⚠️ Çevreyolları ve sınır geçiş hatlarına yakın tenha sokaklar."},
    {"İl_Adı": "Ardahan", "Bölge_Kodu": "TRA", "Bölge_Adı": "Kuzeydoğu Anadolu", "Kritik_Bolgeler": "⚠️ Tenha sokaklar ve kışın ıssızlaşan dış mahalleler."},
    {"İl_Adı": "Malatya", "Bölge_Kodu": "TRB", "Bölge_Adı": "Ortadoğu Anadolu", "Kritik_Bolgeler": "⚠️ Kenar mahalleler ve sanayi çevresi kuytuları."},
    {"İl_Adı": "Elazığ", "Bölge_Kodu": "TRB", "Bölge_Adı": "Ortadoğu Anadolu", "Kritik_Bolgeler": "⚠️ Issız eski mahalleler ve istasyon arkası."},
    {"İl_Adı": "Bingöl", "Bölge_Kodu": "TRB", "Bölge_Adı": "Ortadoğu Anadolu", "Kritik_Bolgeler": "⚠️ Çevreyolu arkaları ve kırsal bağlantı yolları."},
    {"İl_Adı": "Tunceli", "Bölge_Kodu": "TRB", "Bölge_Adı": "Ortadoğu Anadolu", "Kritik_Bolgeler": "⚠️ Issız sokaklar ve nehir kıyısı tenha bölgeler."},
    {"İl_Adı": "Van", "Bölge_Kodu": "TRB", "Bölge_Adı": "Ortadoğu Anadolu", "Kritik_Bolgeler": "⚠️ Dış mahalleler, göç alan kenar yerleşimler ve otogar çevresi."},
    {"İl_Adı": "Muş", "Bölge_Kodu": "TRB", "Bölge_Adı": "Ortadoğu Anadolu", "Kritik_Bolgeler": "⚠️ Kenar mahalleler ve istasyon çevresi."},
    {"İl_Adı": "Bitlis", "Bölge_Kodu": "TRB", "Bölge_Adı": "Ortadoğu Anadolu", "Kritik_Bolgeler": "⚠️ Issız parklar ve eski şehir merkezinin kuytu sokakları."},
    {"İl_Adı": "Hakkari", "Bölge_Kodu": "TRB", "Bölge_Adı": "Ortadoğu Anadolu", "Kritik_Bolgeler": "⚠️ Tenha sınır ve engebeli dış mahalle hatları."},
    {"İl_Adı": "Adıyaman", "Bölge_Kodu": "TRC", "Bölge_Adı": "Güneydoğu Anadolu", "Kritik_Bolgeler": "⚠️ Şehir dışı ücra mahalleler ve kuytu alanlar."},
    {"İl_Adı": "Kilis", "Bölge_Kodu": "TRC", "Bölge_Adı": "Güneydoğu Anadolu", "Kritik_Bolgeler": "⚠️ Eski sanayi çevresi ve sınır göçü alan tenha arka mahalleler."},
    {"İl_Adı": "Şanlıurfa", "Bölge_Kodu": "TRC", "Bölge_Adı": "Güneydoğu Anadolu", "Kritik_Bolgeler": "⚠️ Düzensiz yerleşim bölgeleri, Eyyübiye'nin bazı ücra mahalleleri ve tenha ara sokaklar."},
    {"İl_Adı": "Mardin", "Bölge_Kodu": "TRC", "Bölge_Adı": "Güneydoğu Anadolu", "Kritik_Bolgeler": "⚠️ Yeni şehir kısmındaki bazı tenha parklar ve eski Mardin'in ıssız labirent sokakları."},
    {"İl_Adı": "Batman", "Bölge_Kodu": "TRC", "Bölge_Adı": "Güneydoğu Anadolu", "Kritik_Bolgeler": "⚠️ İluh mahallesi çevresi ve bazı eski kenar yerleşim birimleri."},
    {"İl_Adı": "Şırnak", "Bölge_Kodu": "TRC", "Bölge_Adı": "Güneydoğu Anadolu", "Kritik_Bolgeler": "⚠️ Sınır bölgelerine yakın tenha sokaklar ve çevre yolu bağlantıları."},
    {"İl_Adı": "Siirt", "Bölge_Kodu": "TRC", "Bölge_Adı": "Güneydoğu Anadolu", "Kritik_Bolgeler": "⚠️ Kenar mahalleler ve gece aydınlatması yetersiz kuytu sokaklar."}
]
df_iller = pd.DataFrame(iller_listesi)


def nokta_atisi_analiz(secilen_il, secilen_suc):
    il_satiri = df_iller[df_iller["İl_Adı"] == secilen_il]
    if il_satiri.empty:
        return "Seçilen il bulunamadı.", None

    bolge_kodu = il_satiri.iloc[0]["Bölge_Kodu"]
    bolge_adi = il_satiri.iloc[0]["Bölge_Adı"]
    kritik_yerler = il_satiri.iloc[0]["Kritik_Bolgeler"]

    sucre_satiri = df_suclar[df_suclar["Bölge_Kodu"] == bolge_kodu]
    oran = sucre_satiri.iloc[0][secilen_suc]

    bilgi_notu = f"""
    ### 📊 RESMİ İSTATİSTİKLER
    * 📌 **Seçilen İl:** {secilen_il}
    * 🌍 **TÜİK İBBS Bölgesi:** {bolge_adi} ({bolge_kodu})
    * 🔎 **İncelenen Suç:** {secilen_suc}
    * 📈 **Bu Bölgedeki Türkiye Geneli Dağılım Oranı:** %{oran}

    ---

    ### 🚨 SOSYAL MEDYA & FORUM ANALİZİ (DİKKAT EDİLMESİ GEREKEN YERLER)
    *Ekşi Sözlük, Şikayet Var ve mahalle bazlı asayiş yorumlarından derlenmiştir:*

    {kritik_yerler}

    > **Güvenlik Notu:** Özellikle yalnız yürüyen genç kızlar, öğrenciler ve yabancılar için bu belirtilen ilçe/mahallelerin loş ara sokakları, ıssız parkları ve gece saatlerindeki toplu taşıma durak çevresi 'Yüksek Risk' kategorisinde değerlendirilmektedir. Mümkün mertebe ana caddelerin kullanılması önerilir.
    """

    suc_sutunlari = [col for col in df_suclar.columns if col not in ["Bölge_Kodu", "Bölge_Adı"]]
    tum_oranlar = sucre_satiri[suc_sutunlari].iloc[0].to_dict()
    sonuc_df = pd.DataFrame(list(tum_oranlar.items()), columns=["Suç Türü", "Oran (%)"])

    return bilgi_notu, sonuc_df


il_listesi = sorted(df_iller["İl_Adı"].tolist())
suc_listesi = [col for col in df_suclar.columns if col not in ["Bölge_Kodu", "Bölge_Adı"]]

with gr.Blocks(theme=gr.themes.Soft()) as arayuz:
    gr.Markdown("# ⚖️ Kadın ve Genç Güvenliği - Bölgesel Adalet Analiz Paneli")
    gr.Markdown("Hem TÜİK/Adalet Bakanlığı verilerini hem de halkın sosyal medyadaki (Ekşi Sözlük vb.) bölge yorumlarını bir arada sunan entegre panel.")

    with gr.Row():
        with gr.Column(scale=1):
            il_secimi = gr.Dropdown(choices=il_listesi, label="1. Şehir Seçiniz", value="İstanbul")
            suc_secimi = gr.Dropdown(choices=suc_listesi, label="2. Suç Türü Seçiniz", value="Kasten Öldürme")
            analiz_butonu = gr.Button("Analiz Et", variant="primary")

        with gr.Column(scale=2):
            metin_cikisi = gr.Markdown("### Sonuç Ekranı\nLütfen sol taraftan il ve suç türü seçimi yaptıktan sonra **'Analiz Et'** butonuna basın.")
            tablo_cikisi = gr.Dataframe(headers=["Suç Türü", "Oran (%)"], interactive=False)

    analiz_butonu.click(
        fn=nokta_atisi_analiz,
        inputs=[il_secimi, suc_secimi],
        outputs=[metin_cikisi, tablo_cikisi]
    )

if __name__ == "__main__":
    arayuz.launch(debug=True)